### ISSUE TITLE
Messages during install

### ISSUE THREAD

**Issue by fullbright** [philcryer/lipsync#13]
During install (running install.sh) we don't have the error message when :
- lua is not installed
- lsynd is not installed
- path to lsync / lua  is not valid

An error message should be great to debug.

**Comment by chungyan5** [comment]
hi all

I faced these two errors during install, and i modified the install.sh for suggestion and share:
- cannot find the /usr/local/bin/lsyncd, since i use "https://launchpad.net/ubuntu/+source/lsyncd deb" instead of "wget http://lsyncd.googlecode.com/files/lsyncd-2.0.3.tar.gz"
- wrong privilege in ~/.lipsyncd/lipsyncd.log, it created by root, then access by normal user, then it is wrong. 

in deploy(), i modified as:

<pre>
... 
    echo -n "   > /usr/local/bin/lipsyncd..."
    # using "https://launchpad.net/ubuntu/+source/lsyncd deb" instead of "wget http://lsyncd.googlecode.com/files/lsyncd-2.0.3.tar.gz"  
    ################################################
##  if [ -x  /usr/local/bin/lsyncd ]; then
##      ln -s /usr/local/bin/lsyncd /usr/local/bin/lipsyncd
##  fi
    if [ -x  /usr/bin/lsyncd ]; then
        ln -s /usr/bin/lsyncd /usr/local/bin/lipsyncd
    fi
    echo "done"
... 
    echo -n "   > /home/$username/.lipsyncd/lipsyncd.log..."
    touch /home/$username/.lipsyncd/lipsyncd.log
    chmod g+w /home/$username/.lipsyncd/lipsyncd.log
    # release the log file to be a normal user mode  
    ################################################
    chown $username:$username /home/$username/.lipsyncd/lipsyncd.log
    echo "done"

    echo -n "   > checking for $lipsync_dir_local..."
    if [ ! -d $lipsync_dir_local ]; then
        echo; echo -n " > $lipsync_dir_local not found, creating..."
        mkdir $lipsync_dir_local
        chown $username:$username $lipsync_dir_local
    fi
    echo "done"
</pre>

**Comment by philcryer** [comment]
this is fixed, we check for lsyncd, and for it to be installed lua has to be installed so this is covered. What we need now is to have install check that the user is running 2.x, since 1.x (which is still current in debian (squeeze I think)) won't work with our newer versions of lipsync. I'll open a new bug for this.

Thanks!
