### ISSUE TITLE
Error while changing the local sync directroy

### ISSUE THREAD

**Issue by fullbright** [philcryer/lipsync#14]
When we change the local path in /etc/lipsyncd, the files are erased on the server. We loose files.

It might be cool if the existing local files are pushed to the server and the remote one are pulled. We can handle it that way.

**Comment by philcryer** [comment]
I've changed the installer so that at the end of the install it does a sync of the local and remote dirs, but as a true sync; neither one 'wins' so nothing is deleted. So, if you change a path later this same thing should happen; on a first run - or a run where one of the dirs hasn't been dealt with before, it should do the sync so that neither 'win', and after that deal with things normally from there. Let me think about this one, it's complicated, but I think needed.
