### ISSUE TITLE
Local and remote directory names

### ISSUE THREAD

**Issue by fullbright** [philcryer/lipsync#16]
To be able to sync two directories, they (the remote and the local) must have the same name.

Is it possible to sync directories with different names ?

**Comment by philcryer** [comment]
Sure it's possible, it's the username that needs to be the same on both, and really we can change that later. Right now it prompts you during install for directory names for both the local and remote, and they can be different, it doesn't matter. If you've already installed just edit the file /etc/lipsyncd

LOCAL_DIR=/home/phil/sync/
REMOTE_DIR=/home/phil/someotherdir

Please reopen this if this doesn't answer your question - thanks!

**Comment by Thynix** [comment]
I think the reason for this problem is due to this line in install.sh:
`su $USER_NAME -c 'rsync -rav --stats --log-file=/home/'$USER_NAME'/.lipsyncd/lipsyncd.log -e "ssh -l '$USER_NAME' -p '$SSH_PORT'" '$REMOTE_HOST':'$LOCAL_DIR' '$REMOTE_DIR''`

It looks like it should be
`su $USER_NAME -c 'rsync -rav --stats --log-file=/home/'$USER_NAME'/.lipsyncd/lipsyncd.log -e "ssh -l '$USER_NAME' -p '$SSH_PORT'" '$REMOTE_HOST':'$REMOTE_DIR' '$LOCAL_DIR''`
