### ISSUE TITLE
overwrites crontab for user

### ISSUE THREAD

**Issue by jrullo** [philcryer/lipsync#33]
I used to have jobs in my crontab for the user given for the install, after running the install script, they are all gone and replaced by the one for lipsync. I'm not sure if I missed a question in the install process or if this is default behavior. I ran the install script on Debian 6.

**Comment by Thynix** [comment]
If you ran it as root, the reason for the bug is in line 157: 
`(crontab -l; echo "$newcronjob") | crontab -u $username -`
In your case (as in mine) it sounds like the install script listed the empty root crontab, then appended the lipsync line to it. The line should be changed to
`(crontab -u $username -l; echo "$newcronjob") | crontab -u $username -`

**Comment by philcryer** [comment]
fixed per this commit: https://github.com/philcryer/lipsync/commit/14b5edf0f99eb9487faf8a4bbf225234d6b96f9f#diff-2

Thanks Thynix!
